// Print each tool's annotations with the written justification for every hint,
// as Markdown ready to paste into OpenAI's plugin portal (which asks for a
// justification per readOnlyHint / destructiveHint / openWorldHint).
//
//   npx tsx scripts/annotations-report.ts --profile openai   (default)
//   npx tsx scripts/annotations-report.ts --profile full
//   npm run annotations -- --profile openai > annotations.md
//
// Source of truth: src/tools/_policy.ts. Regenerate after editing a row.

import { TOOL_POLICY } from "../src/tools/_policy.js";
import { allToolDefinitions } from "../src/tools/index.js";
import { isProfile } from "../src/profiles.js";

const argv = process.argv.slice(2);
const flag = argv.indexOf("--profile");
const profile = flag >= 0 ? argv[flag + 1] : "openai";
if (!isProfile(profile)) {
  process.stderr.write(`Unknown profile "${String(profile)}". Use --profile openai or --profile full.\n`);
  process.exit(2);
}

// Definition order (the order tools/list uses). The debug tool is only
// registered with MCP_ENABLE_DEBUG_TOOLS=1, so it never appears here.
const rows = allToolDefinitions
  .map((t) => TOOL_POLICY[t.name])
  .filter((p): p is NonNullable<typeof p> => !!p && p.profiles.includes(profile))
  .filter((p) => p.name !== "versely_render_test_card");

const cell = (s: string) => s.replace(/\|/g, "\\|");

let md = `# Versely MCP — tool annotations (${profile} profile)\n\n`;
md += `${rows.length} tools. Generated by \`scripts/annotations-report.ts\` from \`src/tools/_policy.ts\`.\n\n`;
md += "| Tool | Title | readOnlyHint | destructiveHint | openWorldHint |\n";
md += "|---|---|---|---|---|\n";
for (const p of rows) {
  const a = p.annotations;
  md += `| \`${p.name}\` | ${cell(p.title)} | ${a.readOnlyHint} | ${a.destructiveHint} | ${a.openWorldHint} |\n`;
}
md += "\n## Justifications\n\n";
for (const p of rows) {
  const a = p.annotations;
  md += `### \`${p.name}\` — ${p.title}\n\n`;
  md += `- **readOnlyHint: ${a.readOnlyHint}** — ${p.justifications.readOnly}\n`;
  md += `- **destructiveHint: ${a.destructiveHint}** — ${p.justifications.destructive}\n`;
  md += `- **openWorldHint: ${a.openWorldHint}** — ${p.justifications.openWorld}\n`;
  if (profile === "openai" && p.invoking && p.invoked) {
    md += `- Status lines: "${p.invoking}" / "${p.invoked}"\n`;
  }
  md += "\n";
}

process.stdout.write(md);
