// Auto-generates TOOLS.md from the registered tool definitions.
// Run via `npm run docs` after adding or modifying tools.

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { zodToJsonSchema } from "zod-to-json-schema";
import type { Tool } from "../src/tools/_types.js";
import { TOOL_POLICY } from "../src/tools/_policy.js";
import { userTools } from "../src/tools/user.js";
import { generateTools } from "../src/tools/generate.js";
import { slideshowTools } from "../src/tools/slideshow.js";
import { movieTools } from "../src/tools/movie.js";
import { ugcTools } from "../src/tools/ugc.js";
import { socialTools } from "../src/tools/social.js";
import { statusTools } from "../src/tools/status.js";
import { featuresTools } from "../src/tools/features.js";
import { workflowTools } from "../src/tools/workflows.js";
import { videoWorkflowTools } from "../src/tools/videoWorkflows.js";
import { voiceTools } from "../src/tools/voices.js";
import { dubbingTools } from "../src/tools/dubbing.js";
import { automationTools } from "../src/tools/automations.js";
import { audioTools } from "../src/tools/audio.js";
import { billingTools } from "../src/tools/billing.js";
import { avatarTools } from "../src/tools/avatars.js";
import { brandTools } from "../src/tools/brands.js";

// Every registered tool, in tools/list order. (The env-gated debug tool is
// left out: it isn't registered unless MCP_ENABLE_DEBUG_TOOLS=1.)
const categories: Array<[string, Tool[]]> = [
  ["User & Account", userTools],
  ["Billing & subscription", billingTools],
  ["Generation (image / video / audio / music)", generateTools],
  ["Music + sound effects", audioTools],
  ["Avatars (for avatar lip-sync)", avatarTools],
  ["Slideshow", slideshowTools],
  ["Brands", brandTools],
  ["Movie (multi-scene)", movieTools],
  ["UGC (overlays + captions)", ugcTools],
  ["Social media", socialTools],
  ["Status / async polling", statusTools],
  ["Utilities", featuresTools],
  ["Workflows", workflowTools],
  ["Video-workflow runs", videoWorkflowTools],
  ["Voices", voiceTools],
  ["Dubbing", dubbingTools],
  ["Automations", automationTools],
];

interface JsonSchemaProp {
  type?: string | string[];
  enum?: unknown[];
  format?: string;
  items?: JsonSchemaProp;
  description?: string;
  default?: unknown;
  minimum?: number;
  maximum?: number;
}

function describeType(prop: JsonSchemaProp | undefined): string {
  if (!prop) return "any";
  if (prop.enum) {
    return `enum(${prop.enum.map((v) => JSON.stringify(v)).join(" \\| ")})`;
  }
  if (prop.type === "array") {
    return `${describeType(prop.items)}[]`;
  }
  if (prop.format === "uri") return "string (url)";
  if (Array.isArray(prop.type)) return prop.type.join(" \\| ");
  return prop.type ?? "any";
}

function escapeCell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\r?\n/g, " ").trim();
}

function renderTool(tool: Tool): string {
  const schema = zodToJsonSchema(tool.inputSchema, {
    $refStrategy: "none",
    target: "openApi3",
  }) as { properties?: Record<string, JsonSchemaProp>; required?: string[] };

  const policy = TOOL_POLICY[tool.name];
  let out = `### \`${tool.name}\`\n\n`;
  if (policy) {
    const a = policy.annotations;
    const hints = [
      a.readOnlyHint ? "read-only" : null,
      a.destructiveHint ? "destructive" : null,
      a.openWorldHint ? "open-world" : null,
    ].filter(Boolean);
    out += `**${policy.title}** · ${policy.class}${hints.length ? ` (${hints.join(", ")})` : ""}`;
    out += policy.profiles.includes("openai") ? " · also in the ChatGPT plugin\n\n" : "\n\n";
  }
  out += `${tool.description}\n\n`;

  const props = schema.properties ?? {};
  const fields = Object.entries(props);
  if (fields.length === 0) {
    out += "_No input parameters._\n\n";
    return out;
  }

  const required = new Set(schema.required ?? []);
  out += "| Field | Type | Required | Description |\n";
  out += "|-------|------|----------|-------------|\n";
  for (const [name, prop] of fields) {
    const typeStr = describeType(prop);
    const reqMark = required.has(name) ? "**yes**" : "—";
    const desc = prop.description ? escapeCell(prop.description) : "";
    out += `| \`${name}\` | ${typeStr} | ${reqMark} | ${desc} |\n`;
  }
  out += "\n";
  return out;
}

const totalTools = categories.reduce((n, [, t]) => n + t.length, 0);
const pluginTools = categories.reduce(
  (n, [, t]) => n + t.filter((tool) => TOOL_POLICY[tool.name]?.profiles.includes("openai")).length,
  0,
);
const today = new Date().toISOString().slice(0, 10);

let md = `# Versely MCP Tool Catalog

> Auto-generated by \`npm run docs\` on ${today}. Do not edit by hand — regenerate after changing any tool definition.

**${totalTools} tools** across **${categories.length} categories** (the full profile — claude.ai, Claude Code, Cursor, API keys). ${pluginTools} of them are also in the ChatGPT plugin's \`openai\` profile, where some inputs are hidden and model lists are limited to the models the plugin can serve (see README → Profiles).

Async generation tools default to \`mode: "submit"\`: they return a \`request_id\` right away while the job runs in the background. Hosts that render the inline media card update it by themselves; otherwise check the job with \`versely_get_task_status\`. \`mode: "wait"\` blocks for at most ~70 seconds and is not offered to ChatGPT.

## Contents

`;

for (const [title] of categories) {
  const anchor = title
    .toLowerCase()
    .replace(/[^a-z0-9 -]/g, "")
    .replace(/\s+/g, "-");
  md += `- [${title}](#${anchor})\n`;
}
md += "\n";

for (const [title, tools] of categories) {
  md += `## ${title}\n\n_${tools.length} tools_\n\n`;
  for (const tool of tools) {
    md += renderTool(tool);
  }
}

const outPath = resolve(process.cwd(), "TOOLS.md");
writeFileSync(outPath, md, "utf8");
process.stdout.write(`Wrote ${outPath} (${totalTools} tools, ${md.length} bytes)\n`);
