// Auto-generates TOOLS.md from the registered tool definitions.
// Run via `npm run docs` after adding or modifying tools.

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { zodToJsonSchema } from "zod-to-json-schema";
import type { Tool } from "../src/tools/_types.js";
import { userTools } from "../src/tools/user.js";
import { generateTools } from "../src/tools/generate.js";
import { slideshowTools } from "../src/tools/slideshow.js";
import { movieTools } from "../src/tools/movie.js";
import { ugcTools } from "../src/tools/ugc.js";
import { socialTools } from "../src/tools/social.js";
import { statusTools } from "../src/tools/status.js";
import { featuresTools } from "../src/tools/features.js";

const categories: Array<[string, Tool[]]> = [
  ["User & Account", userTools],
  ["Generation (image / video / audio / music)", generateTools],
  ["Slideshow", slideshowTools],
  ["Movie (multi-scene)", movieTools],
  ["UGC (overlays + captions)", ugcTools],
  ["Social media", socialTools],
  ["Status / async polling", statusTools],
  ["Utilities", featuresTools],
];

interface JsonSchemaProp {
  type?: string | string[];
  enum?: unknown[];
  format?: string;
  items?: JsonSchemaProp;
  description?: string;
  default?: unknown;
  minimum?: number;
  maximum?: number;
}

function describeType(prop: JsonSchemaProp | undefined): string {
  if (!prop) return "any";
  if (prop.enum) {
    return `enum(${prop.enum.map((v) => JSON.stringify(v)).join(" \\| ")})`;
  }
  if (prop.type === "array") {
    return `${describeType(prop.items)}[]`;
  }
  if (prop.format === "uri") return "string (url)";
  if (Array.isArray(prop.type)) return prop.type.join(" \\| ");
  return prop.type ?? "any";
}

function escapeCell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\r?\n/g, " ").trim();
}

function renderTool(tool: Tool): string {
  const schema = zodToJsonSchema(tool.inputSchema, {
    $refStrategy: "none",
    target: "openApi3",
  }) as { properties?: Record<string, JsonSchemaProp>; required?: string[] };

  let out = `### \`${tool.name}\`\n\n${tool.description}\n\n`;

  const props = schema.properties ?? {};
  const fields = Object.entries(props);
  if (fields.length === 0) {
    out += "_No input parameters._\n\n";
    return out;
  }

  const required = new Set(schema.required ?? []);
  out += "| Field | Type | Required | Description |\n";
  out += "|-------|------|----------|-------------|\n";
  for (const [name, prop] of fields) {
    const typeStr = describeType(prop);
    const reqMark = required.has(name) ? "**yes**" : "—";
    const desc = prop.description ? escapeCell(prop.description) : "";
    out += `| \`${name}\` | ${typeStr} | ${reqMark} | ${desc} |\n`;
  }
  out += "\n";
  return out;
}

const totalTools = categories.reduce((n, [, t]) => n + t.length, 0);
const today = new Date().toISOString().slice(0, 10);

let md = `# Versely MCP Tool Catalog

> Auto-generated by \`npm run docs\` on ${today}. Do not edit by hand — regenerate after changing any tool definition.

**${totalTools} tools** across **${categories.length} categories**. All async generation tools default to \`mode: "wait"\` (poll until done) — pass \`mode: "submit"\` to fire-and-forget and poll later via \`versely_get_task_status\` / \`versely_wait_for_task\`.

## Contents

`;

for (const [title] of categories) {
  const anchor = title
    .toLowerCase()
    .replace(/[^a-z0-9 -]/g, "")
    .replace(/\s+/g, "-");
  md += `- [${title}](#${anchor})\n`;
}
md += "\n";

for (const [title, tools] of categories) {
  md += `## ${title}\n\n_${tools.length} tools_\n\n`;
  for (const tool of tools) {
    md += renderTool(tool);
  }
}

const outPath = resolve(process.cwd(), "TOOLS.md");
writeFileSync(outPath, md, "utf8");
process.stdout.write(`Wrote ${outPath} (${totalTools} tools, ${md.length} bytes)\n`);
